### PR TITLE
Create a cpanfile for dependency management

### PR DESCRIPTION
**Pull request by andrewyatz**
Just making sure no one disagrees with this cpanfile going onto master

### CODE REVIEW

**Comment by muffato** [comment]
since you're asking for it :) Why do you require JSON::XS ? Does JSON not provide a working implementation ?

**Comment by andrewyatz** [comment]
It provides a working impl but it’s not as fast as JSON::XS. Happy to keep the dependency at JSON if you’d prefer

**Comment by andrewyatz** [comment]
BTW I should say this is a change so reseq informatics can install the Git modules we've developed into a cpanminus installation.

**Comment by muffato** [comment]
JSON::XS is indeed faster, but since it's not a mandatory requirement of ensembl-io, should we put JSON in the requirements and JSON::XS in the recommendations ? I wonder how other projects deal with that

PS: I don't mind having JSON::XS in cpanfile, I'm still very happy with having such a file :)

**Comment by andrewyatz** [comment]
Fair comment. JSON::XS in recommended and JSON in required. Also this is ensembl-git-tools not ensembl-io :).

**Comment by muffato** [comment]
I'm mixing the PRs :)

**Pull request merged**
