### PR TITLE
Altered file to use backwards compatible readdir call

### PR DESCRIPTION
**Pull request by cganote**
Your documentation says that it supports perl 5.10, but the readdir call that automatically assigns to $_ wasn't introduced until 5.12.

### CODE REVIEW

**Comment by muffato** [comment]
Dear @cganote,

This is a useful contribution. We indeed want to support Perl 5.10 and the change is straightforward. Can I ask you to reformat the function to stick to the original indentation style (2 spaces) ? Reading the history of the file would be easier that way.

Thank you,
Matthieu

**Comment by cganote** [comment]
Hi Matthieu,

Sorry about that. I was trying to read it better. I think it's in better shape now, I committed to my own repo. Should I create a new pull request?

-Carrie

**Comment by muffato** [comment]
No worries :)
Magic of github, you don't need to do anything, this pull-request has already picked up the change.

The pull-request is now fine by me, I'll let someone else double-check and hit the merge button.

Thank you !
Matthieu

**Comment by magaliruffier** [comment]
thanks for the fix, I think it is already catching other users out

**Pull request merged**
