### PR TITLE
Add Rapid Release site

### PR DESCRIPTION
**Pull request by msmanoj**
Added the Rapid Release group to the `git-ensembl` script.

Related JIRA:
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6174

### CODE REVIEW

**Review by ens-ap5 — APPROVED** [review]
That looks reasonable. I don't think we'll ever have any funcgen data on rapid, but the webcode might complain if the API's not there

**Comment by magaliruffier** [comment]
do we need to add ensembl-taxonomy as well? I think it has become a pre-requisite for the Perl API, someone from Production might be able to confirm

**Comment by ens-ap5** [comment]
Hi Mag

It’s not required for running the website - we don’t use it in our sandboxes. It may be required by utilities that we don’t normally run.

Cheers

Anne

**Comment by magaliruffier** [comment]
Great, thanks for confirming

**Pull request merged**
